### ISSUE TITLE
cleveref package before hyperref package

### ISSUE THREAD

**Issue by pramodhyapa** [PAGSA/ThesisTemplate#10]
in use_packages.tex the order of the last 2 packages needs to be changed from,

`
\usepackage{cleveref}
\usepackage[]{hyperref}
\hypersetup{
	colorlinks,
	linkcolor={blue},
	citecolor={red},
	urlcolor={olive}
}`

to

`\usepackage[]{hyperref}
\hypersetup{
	colorlinks,
	linkcolor={blue},
	citecolor={red},
	urlcolor={olive}
}
\usepackage{cleveref}`

Equation references do not work when this is in the current order

**Comment by calebmiller** [comment]
done
