### ISSUE TITLE
centering on Title page

### ISSUE THREAD

**Issue by pramodhyapa** [PAGSA/ThesisTemplate#13]
In titlepage.tex, the alignment of 'University of Victoria' is left when it should be centered

So change,
```
	\begin{tabular}{cl}
		& \copyright\ \yourname, 2017\\
		& \phantom{\copyright} University of Victoria
	\end{tabular}

```
to 

```
	\begin{tabular}{cc}
		& \copyright\ \yourname, 2017\\
		& \phantom{\copyright} University of Victoria
	\end{tabular}
```

**Comment by calebmiller** [comment]
l or c made no difference for me. I'm not sure why the table is implemented in the first place. Swapped for a center environment in latest commit
