### ISSUE TITLE
External examiner name should be removed from supervisory committee  

### ISSUE THREAD

**Issue by OClarkson** [PAGSA/ThesisTemplate#15]
https://www.uvic.ca/graduatestudies/assets/docs/docs/thesis/Thesis%20format%20checklist%20and%20sample%20pages%20-%20UVic%202016.pdf says an external examiner is not be to included on this list

**Comment by calebmiller** [comment]
I don't see the external currently on the template. Just the outside member who is a potential member of the supervisory committee. If I'm mistaken let me know

**Comment by OClarkson** [comment]
I misinterpreted it then. You're right.
