### ISSUE TITLE
Glossary list missing and bibliographystyle not valid

### ISSUE THREAD

**Issue by asadmzmn** [PAGSA/ThesisTemplate#21]
1. On the Fedora Linux computer while compiling the source code the glossary list didn't appear until the syntax changed to `\usepackage[automake]{glossaries}` in Glossary.tex.
2. Also, the  `\bibliographystyle{ieetr}` is not valid either on Overleaf or local installation of `LaTex` it changed the syntax to `\bibliographystyle{IEEEtran}` in ThesisMain.tex.

**Comment by calebmiller** [comment]
fixed in commits a7b88ab61be05ee14f39f7585183d20abb647672 and 5a5579eb5002764cdbdb4d5fc824c4b159d08afc respectively
