### ISSUE TITLE
frontmatter/title.tex commands for name and supervisory committee

### ISSUE THREAD

**Issue by pramodhyapa** [PAGSA/ThesisTemplate#4]
frontmatter/title.tex has the following commands

\newcommand{\yourname}{NAME}
\newcommand\thesistitle{TITLE}
% One needs to make adjustments for a Master's Thesis
\newcommand\nameanddegrees{%
\yourname\\
 University, 2015}
\newcommand\panel{%
\HRule\\\panelist{Dr.  R. SUpervisor}{Supervisor}{Department of Physics and Astronomy}
\HRule\\\panelist{Dr. M.\ Member One}{Departmental Member}{Department of Same As Candidate}
\HRule\\\panelist{Dr. Member Two}{Departmental Member}{Department of Same As Candidate}
\HRule\\\panelist{Dr. Outside Member}{Outside Member}{Department of Not Same As Candidate}}

However they don't update the title page. The setup.tex file has the same code and actually updates the title page

**Comment by calebmiller** [comment]
Should be fixed. title.tex was obsolete but wasn't deleted
